### ISSUE TITLE
Governance Votes Improvements

### ISSUE THREAD

**Issue by drewcook** [aave/interface#1267]
**Is your feature request related to a problem? Please describe.**

On the first iteration of implementing governance voters list, there have been several things that have stuck out that we want to capture as improvements to this first iteration.  This issue represents all of those issues or improvements that can be made.

1. Swap out using the backend API and MongoDB table of governance users to using the build cache + on-chain events.
2. Leverage using the Twitter ENS avatars, but instead of storing external URLs of the images for both Twitter and ENS, store them as base64 images directly so that external requests don't need to happen on the client for each user.  This is the reason we did not go through with ENS avatars, as most users do not have one set, even though they did have an ENS name.  Therefore, the value for the ENS avatar was to a non-existent image, so there were hundreds of 404 requests happening.  These would be better stored directly in the DB if we continue to use that as the source for data.
3. Rounding errors for voting numbers.4. 
4. Handle text overflow. See proposal 109 for an example, on mobile especially. This might be causing issues on some mobile devices with the voters list modal.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by drewcook** [comment]
@sakulstra Would you like to add any notes here?  Particularly #3 and anything else you'd like to add.

**Comment by sakulstra** [comment]
okay just rephrasing what i wrote in dm before.

Regarding 3. I think the current design doesn't justify the needs and makes this kinda unusable (still using alternative UIs and onchain data is this is not really helpful).

![image](https://user-images.githubusercontent.com/4396533/197337000-6c63d8bc-e696-4e2b-8400-0a46811301f8.png)

The things that are important information imo in order of priority

### power information
How many votes/much power did a certain address have.
This information is broken here - the ui rounds away votes (in this case close to 10k power on a single vote).
This is annoying in the votes breakdown, but perhaps even worse in the summary because the ui showed 3.2M for votes long before there were 3.2M which worse case could have lead to the proposal failing (it didn't because in this case ppl were very closely watching and keeping the community updated via twitter, but the app.aave.com was super misleading in the process).

I guess rounding away decimals could be okay, but besides that "every vote counts"

### time information
when was the vote casted (5 seconds before the voting period ended, right after proposal creation).
It's completely missing in the ui

### vote information
how was the vote casted, through a smart contract an EOA...
There's no link or sth to the vote at all (trust not verify)

### voter information
Who voted (this info can be easily read from "vote information", but not the other way around).
If there is an ens/sybil that's fine, but to be fair from 250 votes on a proposal ~10 have an image and perhaps 20-30 an ens name - it's not that important for the voting process.

---

This alternative ui which is not very beautiful, solves these issues a lot better imo :shrug: 

![image](https://user-images.githubusercontent.com/4396533/197337081-a14f663b-4019-49e1-a64d-7d5893f97b4d.png)

Pro
- vote power is correct
- time information is present
- the vote links to the vote not the user

Con
- it's missing a bit of the voter information (no name or link to the voter, but you can see it on the vote)

The rationale behind that design was that for the most part you are interested in the power/timing and then you might look deeper into the "important/interesting votes".

**Comment by drewcook** [comment]
@sakulstra 🙏 Thank you much for your detailed notes! I agree with a lot of these points, and they would all be great additions to showing the appropriate data regarding governance votes both technically and visually. Many of these points were not included in the original design, so it will be great to pass these onto our design team for consideration and see how we can better display this through our UI. I think we can take these points and really improve what our first iteration is.

If anyone has anything else they’d like to add here, please feel free to comment.

**Comment by grothem** [comment]
I agree we should have a way to view more detailed information in the UI (unrounded values, time, voter info...), but I think that info should be displayed somewhere else. 

One of the things I like about the current UI is how it's easy to glance at and you can quickly get a good idea of the current status. Having unrounded values and adding more info would clutter it up and be harder to skim through. But if there was a link or a section you could expand that had that detailed info, that would be good.

**Comment by sakulstra** [comment]
@grothem very much disagree with that.

From all the important info contained in a vote the current ui exposes the a very tiny part rendered useless and leaving you in a state where you can't even help yourself (no linking to votes).

Wrote it above but am not sure if this was well understood:
i think rounding **down** decimals is perfectly fine.
Rounding up/down by 10k votes is not.
You know that the value scope here is between 0 and <=1.xM. I think it should be possible to find a ui which can properly handle numbers up to `1999999` so that at least the very small problem scope the current ui covers is covered well enough.

**Comment by grothem** [comment]
I understand the rounding. I was just saying that I think it's valuable to have a view that's easy to digest with rounded 'friendly' numbers, and a separate section with more detailed information.
