### ISSUE TITLE
Dear developers ,  I hope you are in good condition.

### ISSUE THREAD

**Issue by fajarMmd** [aave/interface#1476]
*Dear developers ,

I hope you are in good condition. I wanted to contact you to provide some feedback on my experience with the customer service team last. Specifically, I'm struggling to resolve an issue I'm having with my account and the representative I spoke to seems disinterested in helping me.

While I understand that solving problems can be challenging, I believe that the customer service team plays an important role in ensuring customer satisfaction. It would be great if representatives were given more training on how to deal with complex issues and provide a better customer experience.

With that said, I'd like to commend the team's effort in improving the product. The latest improvements are greatly appreciated and have made a positive impact on my experience.

Thanks for taking the time to read my feedback. I hope to see continued improvements in the future.

Greetings,
[dawn]

*Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by defispartan** [comment]
Hi Dawn, thanks for the feedback. 

Since your issue doesn't have any action I'm going to close it, but if you would like further assistance feel free to reach out to wecare@aave.com or check out the [contributing guide](https://github.com/aave/interface/blob/main/CONTRIBUTING.md) to learn more about the Aave interface
