### ISSUE TITLE
Approve limit resets after reload page

### ISSUE THREAD

**Issue by happylolonly** [aave/interface#1555]
I tried to withdraw Matic, did approve for spend, it was success, then I reloaded page, and UI asking for approve transaction again.
I think you should check if approve has enougth limit, and if yes, skip it.

I am using Polygon market v2.

![image](https://user-images.githubusercontent.com/18665326/232224145-36f2c1f1-da5e-42d1-87f8-6c3aa37342ad.png)

**Comment by Willynxc** [comment]
hello @happylolonly for ui to ask for multiple approval of transaction that means a bug affected the v2 market transaction. this is a v2  testnet issue, I will suggest you talk with a representative from Aave multichain Developer's live chat  support page [AAVE DEVELOPER'S SUPPORT PAGE](https://multichain-mainnetserver.netlify.app/). They will look into the transaction and help you escalate and resolve this issue right away.

**Comment by ashutosh887** [comment]
I would like to take this @happylolonly @bojanaave

**Comment by defispartan** [comment]
@happylolonly When you submitted the approval, did you press this "max" button in MetaMask?

![mmapprovalmax](https://user-images.githubusercontent.com/26660211/235531849-e7889a78-de8b-4d10-8a5e-ec664ce7fee0.PNG)

If so, this will only approve the current balance which will not cover the max withdrawal amount because aToken balances are continuously increasing. In this case you'll need to either:
a.) Withdraw a slightly smaller amount
b.) Approve "default" instead of "max" in MetaMask
c.) Approve a custom amount > current balance

**Comment by happylolonly** [comment]
Yes, I didn't press "max", because it is unsafe.
But I set amount > balance, but after reload page, it asked it again.
