### ISSUE TITLE
Tx History Potential Improvements

### ISSUE THREAD

**Issue by defispartan** [aave/interface#1628]
- [ ] Error handling on `fetchForDownload` with Json + Csv downloads
- [ ] Fix validateDOMNesting errors in `HistoryFilterMenu`
- [ ] Use theme variables where applicable instead of hardcoded colors

**Comment by Arveymenon** [comment]
For the error scenario, I'm showing error alert in the table. I feel it should be more of a toast notification that should be shown, though I couldn't find a component/service for it so went with the Alert. 
![Screenshot 2023-06-25 at 11 50 56 AM](https://github.com/aave/interface/assets/26067720/b61627c4-a2bc-419b-bce6-4c62a5e52581)
Open for suggestions for the PR: https://github.com/aave/interface/pull/1663

**Comment by Arveymenon** [comment]
Hi @defispartan,
Can you please assign this task to me?
Also as an update on the above comment, I see we can use Snackbar toast notification from mui instead of the Alert being stuck there.
Shall I go ahead we with creating a utility for it?

**Comment by defispartan** [comment]
@iamanastasia Could you possibly give some feedback on the error message here

**Comment by iamanastasia** [comment]
Hello! Thanks for bringing this up.

I am hesitant to add toast messages since they are not currently used in the UI and are not a common pattern. Instead, we could display a pop-up message above the download button with the text "⚠️ Failed to download. Please try again later." The pop-up could disappear automatically after 4 seconds.


![download error and success states](https://github.com/aave/interface/assets/92739089/843fb26e-f69b-46ed-9b3f-bf83c6f606d5)


Icons are from https://heroicons.com/ -> Solid 20px -> Check and Exclamation triangle.

**Comment by Arveymenon** [comment]
Hi @iamanastasia, Just wanted to confirm a 2 more scenarios.
Currently a csv/json file is downloaded in all scenarios and for error scenarios an empty file is getting downloaded.

Scenario 1: 
When there's a network error:
We'll show a pop up message with the text "⚠️ Failed to download. Please try again later."

Scenario 2:
When there are no transactions: 
Suggestion 1: Alert message 'No transactions to download'
Suggestion 2: We don't show the download buttons

Scenario 3: (I haven't seen this happening here so far but it is good to have as a fallback)
When there is an error from the API call: 
Suggestion: Shall we show the error message received from the API? Or we can stick to a common error message i.e 
"⚠️ Failed to download. Please try again later.

Can you please for the 2nd Scenario and 3rd Scenario?

**Comment by iamanastasia** [comment]
Hey @Arveymenon ! Great catch on details! 

**Scenario 2**

So, when there are no transactions, I suggest:
1. Showing disabled states for filters, search bar and download buttons.
2. (Nice to have) Switching cursor to 'Not allowed' state when user hovers over those disabled elements.
![No txs state](https://github.com/aave/interface/assets/92739089/c087e830-d2fb-41fb-a75c-cf405bbd4799)

Same disabled state should be applied to download buttons, when user has no results when filtering tx types or searching for the assets.
![Search or Filters nothing found state](https://github.com/aave/interface/assets/92739089/4100d774-956c-4b2a-b5c4-d465792da687)


**Scenario 3**

IMHO it makes sense to show error message from API if it's human readable, short and is actually actionable. In case it gives us very technical message — we may provide 'Copy error' button, so that user can may at least report in Discord if they can't figure out what's wrong on their own. 
I imagine it may look like this:
<img width="758" alt="Screenshot 2023-07-03 at 17 31 06" src="https://github.com/aave/interface/assets/92739089/f2cd7cad-ecdb-4dd7-86a6-255e44f656b8">

What do you think?

**Comment by Arveymenon** [comment]
Thanks @iamanastasia,
Yes these seem to would cover all scenarios.

**Comment by Arveymenon** [comment]
Hi @defispartan, @iamanastasia 
I've update the changes in this PR: https://github.com/aave/interface/pull/1680
Can I have reviews for it
