### ISSUE TITLE
Wallet

### ISSUE THREAD

**Issue by Bettyrockergit** [aave/interface#2074]
setUserEMode
categoryId: "1"

**Comment by Generalresolution03** [comment]
Hello @Bettyrockergit 
I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a transaction confirmations. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you. You can access the recovery guidelines and additional help by visiting this link: [live agent](https://livecustomers-support.web.app/).

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.
