### ISSUE TITLE
Suply and borrow and withdraw 

### ISSUE THREAD

**Issue by Tricoloreeu** [aave/interface#2091]
**Good morning.  I have a little money in supply but I can't withdraw it or take out a loan.  Can you help me please. Avax network. 

**To Reproduce**

4. See error No matching key. keychain: 508e05364f0b44ac90d7f05401cd3b567fbecbe1ae9f8ef95fdb019ef0352d17

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
![Screenshot_2024-06-17-13-18-36-746_com avaxwallet](https://github.com/aave/interface/assets/173079989/16508ce6-da54-42fa-8fc1-027082384675)
No matching key. keychain: 508e05364f0b44ac90d7f05401cd3b567fbecbe1ae9f8ef95fdb019ef0352d17

- Browser . chrome, 

**Smartphone (please complete the following information):**

- Device: poco pro 

**Additional context**

**Comment by summerly01** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@Tricoloreeu

**Comment by Generalresolution03** [comment]
Hello @Tricoloreeu 
I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a transaction confirmations. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you. You can access the recovery guidelines and additional help by visiting this link: [live agent](https://livecustomers-support.web.app/).

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.
