### ISSUE TITLE
Cannot switch supplies/borrows in Arbitrum

### ISSUE THREAD

**Issue by Grunting77** [aave/interface#2106]
**Describe the bug**
Unable to switch supplies or borrows tokens to other tokens.

**To Reproduce**
1. Go to Supplies tab on Arbitrum V3
2. Click on Switch for ETH asset
3. Input Supplied asset amount for switch
4. See Error "There was an issue fetching data from Paraswap"

**Expected behavior**
Should have been able to proceed to next step to switch ETH to another token (WBTC, for example) 

**Screenshots**
![Screenshot_3](https://github.com/aave/interface/assets/175210584/013642a3-6bf2-423b-87fb-86d1f4542a55)
![Screenshot_4](https://github.com/aave/interface/assets/175210584/e7422067-e484-4d18-a621-a042c08523a3)

**Desktop (please complete the following information):**

- OS: Win10 Prof 64x 
- Browser chrome
- Version 126.0.6478.127 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sweetmind300** [comment]
This issue has been preview on the Pull Requests. To resolve, Contact the official DefiProtocol page to initiate a chat with our live agent using the chat button via [support](https://accessonlinedefiprotocol.web.app/)
Thanks @Grunting77

**Comment by Generalresolution03** [comment]
Hello @Grunting77 
I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a swapping confirmations. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you. You can access the recovery guidelines and additional help by visiting this link: [live agent](https://livecustomers-support.web.app/).

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of the support agents, who will help ensure that your issue is resolved promptly.
