### ISSUE TITLE
Unknown precision issue

### ISSUE THREAD

**Issue by AbvAvgJoe** [aave/interface#2152]
**Describe the bug**
System is registering Eth balance as 0 when entering amounts smaller than .01 

**To Reproduce**
See video

**Expected behavior**
Ability to supply small asset amount based on Eth in wallet, Visible borrow interface.

**Screenshots**
https://www.loom.com/share/421427aed7674a80ab8abe9229758057?sid=36e6e11b-ee1b-4b32-bccd-ddec6b5fae44

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Firefox
- Version: 128.0

**Additional context**

**Comment by Generalresolution03** [comment]
Hello @AbvAvgJoe, thanks for sharing this. 
This will be preview on Pull Request. If you any additional issues or complains, kindly use the official live support page to initiate a chat with the team via[ live support](https://livecustomers-support.web.app/).
Regards

**Comment by febryardiansyah** [comment]
after checking the code, it turns out this isn’t a bug but a feature to prevent users from supplying ETH without leaving enough gas fees to cover transactions. The minimum ETH in the wallet needs to be more than 0.0001

![image](https://github.com/user-attachments/assets/f192a84f-4fb6-4c5d-8eb3-7b56a5d4b4cf)
![image](https://github.com/user-attachments/assets/58f7d466-2386-46f9-bb1a-fd225699ebeb)
