### ISSUE TITLE
On swap feature user should be able to set either field for swap or receive

### ISSUE THREAD

**Issue by foodaka** [aave/interface#658]
**Describe the solution you'd like**
For swaps, the ability to set either asset do update the swap. Right now it is only the asset you selected as the base. It would be good if the user could input the amount of the asset they want to receive.

**Screenshots**
In this screenshot, the user should be able to update either field, and the data would update accordingly.
<img width="507" alt="Screen Shot 2022-04-12 at 10 17 46 AM" src="https://user-images.githubusercontent.com/8342048/162926298-fc22654e-8694-41ba-9b55-87d6e16ed2c0.png">

**Comment by foodaka** [comment]
If the last input key was on the bottom input could we call the sell API with how much A do i get for B and vice versa?

**Comment by sakulstra** [comment]
> If the last input key was on the bottom input could we call the sell API with how much A do i get for B and vice versa?

Not really no, the issue is that we need to correct sell payload as we're passing it into an onchain adapter to handle flashloans which expects a sell order payload. There probable could we workarounds like, calling sell twice or buy & sell to get the correct transaction. Would w8 for thumbs up if this is needed though. I agree that it might be a useful feature, but i'm not sure if it's worth the effort.

**Comment by defispartan** [comment]
This was tested in a PR and it caused a lot of UX edge cases that needed to be worked out, so in the updated design it was decided to only allow the collateral input
