### ISSUE TITLE
Not an Issue But a Usage Guidance Request Re: Polygon Wallet and Supplying wETH in AAVE

### ISSUE THREAD

**Issue by Marx-Melencio** [aave/interface#691]
Would greatly appreciate guidance on supplying in AAVE my wETH, which is in my Polygon wallet.
I always get "Please switch to Polygon POS" along with "Wrong Network" whenever I try to supply my wETH in my Polygon wallet.
This is despite already selecting, in AAVE, Polygonv3 and even Polygonv2 from the market options.
Please advise. Thanks in advance!

**Comment by sendra** [comment]
This is because your wallet is set on another network, so before supplying you need to change it to Polygon.

Aave interface is built so you can check your positions in other markets / networks without the need to keep changing your connected network in the wallet. But once you want to do any action, if the wallet is not connected to the specified network, it will ask for the change.

**Comment by Marx-Melencio** [comment]
Thanks, @sendra ... Yep, the "Please switch to Polygon POS" refers to the current network selected in the connected wallet. And not the network selected in AAVE (I was looking for a "Polygon POS" network option in AAVE). Perhaps a slight change in wording of the message would make this quickly comprehensible for users, especially those who are only starting to use dApps? Anyway, closing this now.  :)
