### ISSUE TITLE
Restyle repay with collateral modal

### ISSUE THREAD

**Issue by defispartan** [aave/interface#708]
Update to the design specs and get community feedback

**Comment by iamanastasia** [comment]
Hey! Quick suggestion on Repay with collateral design enhancements:
<img width="1408" alt="Screenshot 2022-05-18 at 12 45 02" src="https://user-images.githubusercontent.com/92739089/168997882-2eb03e35-78cd-488b-bae4-37afc34ca7a1.png">

Highlights and probably meaningful details:
1. Price impact and slippage tolerance UI elements (added new style and positions). In my opinion it's a bit easier to see and not very messed up.
2. Showing full 'Borrow balance' and 'Collateral balance' in the inputs instead of 'Available'. Tried 'Available' value with couple of tests, users were confused, because of it. Expectation — to see full balance.  
3. Showing 'Borrow balance' and 'Collateral balance' after repayment -> adds visibility on balances
4. Two main warning messages: about 'Insufficient collateral balance' and 'Zero collateral balance after repayment'. 

Let me know what do you think
