### ISSUE TITLE
stETH seems to not be supported by paraswap, so wont allow swap and repay with collateral options

### ISSUE THREAD

**Issue by sirsoth** [aave/interface#754]
**Describe the bug**
It seems any swap or repay with collateral action with stETH would fail, although that there is swap option available for stETH in paraswap. 

**To Reproduce**
1. Deposit stETH
2. Try to swap or try to repay with collateral using it
3. Error will show up cannot estimate gas; transaction may fail or may require manual gas limit or INSUFFICIENT_BALANCE_BEFORE_SWAP in tenderly

**Expected behavior**
Either showing that the asset is not listed or available for such actiosn (not the optimal UX) or we work somehow to get stETH supported

**Screenshots**

![image](https://user-images.githubusercontent.com/5862694/167388108-e988ebf7-cfeb-4668-9ccb-07872b3bb005.png)

![image](https://user-images.githubusercontent.com/5862694/167388213-2140fa75-5a69-40d2-b5bb-c29006fc2f82.png)

**Comment by sakulstra** [comment]
@sirsoth can you provide an address to reproduce? Just checked and should be supported on paraswap so i guess it's sth different.

**Comment by defispartan** [comment]
Don't share addresses on Github issues

**Comment by defispartan** [comment]
It doesn't look like a Paraswap issue though, for both repay with collateral and collateral swap, the underlying tokens are swapped, not the aTokens, and there does appear to be sufficient liquidity.

The issue is most likely in the calculation of maxRepayableDebt. Because the "exact_out" variant of Paraswap is used, it has an expected amount to receive, and if there's not enough collateral to cover after slippage + price impact then this is likely the cause of the `INSUFFICIENT_BALANCE_BEFORE_SWAP` error.

**Comment by sirsoth** [comment]
Following up on this, maybe would be better to remove stETH from the list of assets available for swap/repay with collateral meanwhile?

**Comment by defispartan** [comment]
stETH has a precision error in the balanceOf function which makes it impossible to use in the flashloan adapter contracts, if a transaction involves a flashloan, it's disabled for this asset and a warning message is shown
